# SQL 1. Базовые запросы

# Домашнее задание 1.1
### Скоро церемония вручения премии «Оскар»!

На первом занятии мы изучили базовые запросы, но этого достаточно, чтобы
разобраться с важной задачей.
Приближается церемония вручения «Оскара». Отдел маркетинга Netflix решил
напомнить пользователям о результатах церемонии 2020 года, а также
рассказать про фильмы и сериалы с участием победителей и номинантов,
которые есть в сервисе. Таким образом они надеятся привлечь новую
аудиторию.


Ваша задача — помочь проверить эту гипотезу и подготовить правильные выборки.

In [7]:
import pandas as pd

### Задачи от отдела маркетинга

#### 1. Вывести названия всех фильмов, в которых участвует Хоакин Феникс (Joaquin Phoenix) — победитель номинации за лучшую мужскую роль.

select *
from netflix
where cast_names like '%Joaquin Phoenix%'

In [27]:
df = pd.read_excel('ДЗ_1.xlsx', sheet_name=0, skiprows=None, nrows=2)
df.head()

,show_id,type,title,director,cast_names,country,date_added,release_year,rating,duration,duration_type,description,listed_in
0,s2701,Movie,Her,Spike Jonze,"Joaquin Phoenix, Scarlett Johansson, Amy Adams...",United States,2018-07-29,2013,R,126,min,Love comes to a lonely writer in the sleekest ...,"Dramas, Romantic Movies, Sci-Fi & Fantasy"
1,s6647,Movie,The Master,Paul Thomas Anderson,"Joaquin Phoenix, Philip Seymour Hoffman, Amy A...",United States,2020-01-14,2012,R,137,min,A heavy-drinking loner finds some semblance of...,"Dramas, Independent Movies"

#### 2. Дать названия всех сериалов, в которых участвует Рене Зеллвегер (Renée Zellweger) — победительница номинации за лучшую женскую роль.

select *
from netflix
where type like 'TV Show'
and cast_names like '%Renée Zellweger%'

In [29]:
df = pd.read_excel('ДЗ_1.xlsx', sheet_name=1, skiprows=None, nrows=1)
df.head()

,show_id,type,title,director,cast_names,country,date_added,release_year,rating,duration,duration_type,description,listed_in
0,s7545,TV Show,WHAT / IF,NaN,"Renée Zellweger, Jane Levy, Blake Jenner, Keit...",United States,2019-05-24,2019,TV-MA,1,Season,Desperate to secure funding for her med tech s...,"TV Dramas, TV Thrillers"

#### 3. Дать всю имеющуюся информацию о не слишком старых фильмах производства Netflix, которые сняли режиссеры пяти главных фильмов 2020 года по версии [«КиноПоиска»](https://www.kinopoisk.ru/awards/oscar/2020/).

Эту задачу нужно перевести на аналитический язык.

Нам нужны все столбцы из базы данных Netflix, которые попадают под условия:
• тип: фильм (Movie);
• режиссер: 5 режиссеров фильмов, указанных в списке «КиноПоиска»;
• год: не слишком старые фильмы и сериалы — это фильмы и сериалы, вышедшие не раньше 2010 года.

Важно: имена режиссеров нужно писать на английском, ведь это база Netflix. 
В нашей базе режиссер «Паразитов» записан как Bong Joon Ho, что незначительно отличается от версии IMDb.

select *
from netflix
Where type ~ 'Movie'
    and director in ('Sam Mendes','Todd Phillips','Quentin Tarantino','Martin Scorsese','Bong Joon Ho')
    and release_year >='2010'

In [38]:
df = pd.read_excel('ДЗ_1.xlsx', sheet_name=2)
df.head(7)

,show_id,type,title,director,cast_names,country,date_added,release_year,rating,duration,duration_type,description,listed_in
0,s1788,Movie,Django Unchained,Quentin Tarantino,"Jamie Foxx, Christoph Waltz, Leonardo DiCaprio...",United States,2020-04-25,2012.0,R,165.0,min,"Accompanied by a German bounty hunter, a freed...","Action & Adventure, Dramas"
1,s2858,Movie,Hugo,Martin Scorsese,"Ben Kingsley, Sacha Baron Cohen, Asa Butterfie...","United Kingdom, United States, France",2020-03-01,2011.0,PG,127.0,min,"Living inside a Paris train station, an orphan...","Children & Family Movies, Dramas"
2,s4599,Movie,Okja,Bong Joon Ho,"Tilda Swinton, Jake Gyllenhaal, An Seo Hyun, P...","South Korea, United States",2017-06-28,2017.0,TV-MA,121.0,min,A gentle giant and the girl who raised her are...,"Action & Adventure, Comedies, Dramas"
3,s5261,Movie,Rolling Thunder Revue: A Bob Dylan Story by Ma...,Martin Scorsese,"Bob Dylan, Allen Ginsberg, Joan Baez, Patti Sm...",United States,2019-06-12,2019.0,TV-MA,142.0,min,"In an alchemic mix of fact and fantasy, Martin...","Documentaries, Music & Musicals"
4,s5685,Movie,Snowpiercer,Bong Joon Ho,"Chris Evans, Song Kang-ho, Ed Harris, John Hur...","South Korea, Czech Republic",2019-05-01,2013.0,R,126.0,min,The Earth's remaining inhabitants are confined...,"Action & Adventure, Cult Movies, International..."
5,s6435,Movie,The Hateful Eight,Quentin Tarantino,"Samuel L. Jackson, Kurt Russell, Jennifer Jaso...",United States,2017-10-25,2015.0,R,168.0,min,"Years after the Civil War, a bounty hunter and...","Action & Adventure, Thrillers"
6,s6508,Movie,The Irishman,Martin Scorsese,"Robert De Niro, Al Pacino, Joe Pesci, Harvey K...",United States,2019-11-27,2019.0,R,209.0,min,Hit man Frank Sheeran looks back at the secret...,Dramas

#### 4. Проверить, есть ли у Netflix фильмы, за игру в которых актеры получили «Оскар» в 2020 году. Передать маркетологам всю имеющуюся информацию об этих фильмах. Имена актеров и названия фильмов можно посмотреть по [по этой ссылке](https://www.kinopoisk.ru/awards/oscar/2020/). В БД нужно проверить только наличие нужного сочетания.

Эту задачу нужно перевести на аналитический язык.

После уточнения вы узнали, что маркетологов интересуют актеры, получившие любую из этих премий: 
за лучшую мужскую роль, 
залучшую женскую роль, 
за лучшую мужскую роль второго плана 
или лучшую женскую роль второго плана.

select *
from netflix
Where (title ~ 'Joker'
    or title ~ 'Judy'
    or title ~ 'Once Upon a Time... in Hollywood'
    or title ~ 'Marriage Story')

In [42]:
df = pd.read_excel('ДЗ_1.xlsx', sheet_name=3)
df.head(3)

,show_id,type,title,director,cast_names,country,date_added,release_year,rating,duration,duration_type,description,listed_in
0,s3216,Movie,Joker,Shirish Kunder,"Akshay Kumar, Sonakshi Sinha, Shreyas Talpade,...",India,2018-08-02,2012.0,TV-PG,98.0,min,A remote village situated neither in India or ...,"Comedies, International Movies, Music & Musicals"
1,s3236,Movie,Judy Moody and the Not Bummer Summer,John Schultz,"Jordana Beatty, Heather Graham, Parris Mostell...",United States,2019-08-08,2011.0,PG,91.0,min,"In this family film, never-dull third-grader J...","Children & Family Movies, Comedies"
2,s3950,Movie,Marriage Story,Noah Baumbach,"Scarlett Johansson, Adam Driver, Laura Dern, A...","United Kingdom, United States",2019-12-06,2019.0,R,137.0,min,Academy Award-nominated filmmaker Noah Baumbac...,Dramas

### Ответ наставника
Добрый день!

4. Корректней в условиях проверять пару  - фильм и актер. Вот так: (title = 'Joker' and cast_names ~ 'Joaquin Phoenix'). А то вдруг выйдет какая-нибудь экранизация фильма Joker с другими актерами.


Остальные задачи выполнены корректно. ДЗ принимаю!